# https://doc.traefik.io/traefik/operations/api/
api:
  dashboard: true
  debug: true
  insecure: true
# https://doc.traefik.io/traefik/middlewares/http/basicauth/
http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "oxblixxx:$2y$05$gnu5SdNy9/M5fvh8rSDKQO4qQHfOGNjxlmseMHbrx4DgTg6r/p6/u"
          - "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"
        headerField: "X-WebAuth-User"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# https://doc.traefik.io/traefik/https/acme/
certificatesResolvers:
  cloudflare:
    acme:
      email: phamust1111@gmail.com #add your email
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

# https://doc.traefik.io/traefik/observability/logs/
# Writing Logs to a File
log:
  filePath: "/home/azureuser/traefik-new/config/log"
  format: json
  level: INFO

# https://doc.traefik.io/traefik/observability/access-logs/
accesslog:
  addInternals: true
  filePath: "/home/azureuser/traefik-new/config/access.log"
  format: json

# https://doc.traefik.io/traefik/observability/tracing/overview/
tracing:
  addInternals: true
